name = "beatbump"
account_id = 'df5cf47a239a85c04bb28b7e797275e7'
compatibility_date = "2023-03-14"
main = "./.cloudflare/worker.js"

[site]
bucket = "./.cloudflare/public"

[env.production]
route = { pattern = "beatbump.io", custom_domain = true }

[env.preview]
route = { pattern = "preview.beatbump.io", custom_domain = true }


build.command = "npm run build"
